name: icon-automation
on:
  push:
    branches:
    - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn config set "strict-ssl" false
    - run: yarn install
    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./src/"
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL_TMP }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN_TMP }}
    - run: yarn generate
    - run: yarn build
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: WeChat Work notification
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
      with:
        msgtype: text
        content: |
          install:  npm i snapmaker-react-icon --latest 更新。
          use: import { IconName } from snapmaker-react-icon
          render:    <IconName size={32} color='green'/>
          view all：https://www.figma.com/file/aMVKvxsgCaiz2ThIqL35y3/luban-icon?node-id=3%3A2
